"""production_flow

Revision ID: 20260911_0019
Revises: 20260911_0018
Create Date: 2026-09-11 21:42:00.809164
"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = '20260911_0019'
down_revision = '20260911_0018'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production_batch', sa.Column('planned_quantity', sa.Numeric(precision=14, scale=6), nullable=True))
    op.add_column('production_batch', sa.Column('actual_quantity', sa.Numeric(precision=14, scale=6), nullable=True))
    op.add_column('production_batch', sa.Column('recipe_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('production_item', sa.Column('storage_id', sa.Uuid(), nullable=True))
    op.add_column('production_item', sa.Column('batch_version', sa.Integer(), nullable=True))
    op.create_foreign_key('production_item_tenant_id_storage_id_fkey', 'production_item', 'storage', ['tenant_id', 'storage_id'], ['tenant_id', 'storage_id'], ondelete='RESTRICT')
    # ### end Alembic commands ###

    op.create_check_constraint('ck_production_planned', 'production_batch', "planned_quantity IS NULL OR (planned_quantity > 0 AND planned_quantity <> 'NaN'::numeric)")
    op.create_check_constraint('ck_production_actual', 'production_batch', "actual_quantity IS NULL OR (planned_quantity IS NOT NULL AND actual_quantity >= 0 AND actual_quantity <= planned_quantity AND actual_quantity <> 'NaN'::numeric)")
    op.create_check_constraint('ck_production_item_location_version', 'production_item', '(storage_id IS NULL) = (batch_version IS NULL)')
    op.execute("CREATE TRIGGER production_item_immutable BEFORE UPDATE OR DELETE ON production_item FOR EACH ROW EXECUTE FUNCTION public.fsos_reject_event_mutation()")
    op.execute("CREATE TRIGGER production_item_no_truncate BEFORE TRUNCATE ON production_item FOR EACH STATEMENT EXECUTE FUNCTION public.fsos_reject_event_mutation()")


def downgrade() -> None:
    op.execute('DROP TRIGGER production_item_immutable ON production_item')
    op.execute('DROP TRIGGER production_item_no_truncate ON production_item')
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE production_batch DROP CONSTRAINT IF EXISTS ck_production_planned')
    op.execute('ALTER TABLE production_batch DROP CONSTRAINT IF EXISTS ck_production_actual')
    op.execute('ALTER TABLE production_item DROP CONSTRAINT IF EXISTS ck_production_item_location_version')
    op.drop_constraint('production_item_tenant_id_storage_id_fkey' , 'production_item', type_='foreignkey')
    op.drop_column('production_item', 'batch_version')
    op.drop_column('production_item', 'storage_id')
    op.drop_column('production_batch', 'recipe_snapshot')
    op.drop_column('production_batch', 'actual_quantity')
    op.drop_column('production_batch', 'planned_quantity')
    # ### end Alembic commands ###
