"""user_role_permission

Revision ID: 20260911_0006
Revises: 20260911_0005
Create Date: 2026-09-11 07:00:27.231460
"""
import sqlalchemy as sa

from alembic import op

revision = '20260911_0006'
down_revision = '20260911_0005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('fullname', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='INACTIVE', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('length(trim(email)) > 0', name='ck_user_email'),
    sa.CheckConstraint('length(trim(username)) > 0', name='ck_user_username'),
    sa.CheckConstraint('version >= 1', name='ck_user_version'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('tenant_id', 'user_id', name='uq_user_tenant_id')
    )
    op.create_index('ix_user_created_at', 'app_user', ['created_at'], unique=False)
    op.create_index('uq_user_tenant_email', 'app_user', ['tenant_id', sa.literal_column('lower(btrim(email))')], unique=True)
    op.create_index('uq_user_tenant_username', 'app_user', ['tenant_id', sa.literal_column('lower(btrim(username))')], unique=True)
    op.create_table('permission',
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('permission_code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('length(trim(permission_code)) > 0', name='ck_permission_code'),
    sa.CheckConstraint('version >= 1', name='ck_permission_version'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('permission_id'),
    sa.UniqueConstraint('tenant_id', 'permission_code', name='uq_permission_tenant_code'),
    sa.UniqueConstraint('tenant_id', 'permission_id', name='uq_permission_tenant_id')
    )
    op.create_index('ix_permission_created_at', 'permission', ['created_at'], unique=False)
    op.create_table('role',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('role_code', sa.String(length=50), nullable=False),
    sa.Column('role_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('length(trim(role_code)) > 0', name='ck_role_code'),
    sa.CheckConstraint('version >= 1', name='ck_role_version'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('tenant_id', 'role_code', name='uq_role_tenant_code'),
    sa.UniqueConstraint('tenant_id', 'role_id', name='uq_role_tenant_id')
    )
    op.create_index('ix_role_created_at', 'role', ['created_at'], unique=False)
    op.create_table('role_permission',
    sa.Column('role_permission_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('version >= 1', name='ck_role_permission_version'),
    sa.ForeignKeyConstraint(['tenant_id', 'permission_id'], ['permission.tenant_id', 'permission.permission_id'], name='fk_role_permission_permission', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'role_id'], ['role.tenant_id', 'role.role_id'], name='fk_role_permission_role', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('role_permission_id'),
    sa.UniqueConstraint('tenant_id', 'role_id', 'permission_id', name='uq_role_permission_pair')
    )
    op.create_index('ix_role_permission_created_at', 'role_permission', ['created_at'], unique=False)
    op.create_index('ix_role_permission_tenant_permission', 'role_permission', ['tenant_id', 'permission_id'], unique=False)
    op.create_table('user_role',
    sa.Column('user_role_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('version >= 1', name='ck_user_role_version'),
    sa.ForeignKeyConstraint(['tenant_id', 'role_id'], ['role.tenant_id', 'role.role_id'], name='fk_user_role_role', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'user_id'], ['app_user.tenant_id', 'app_user.user_id'], name='fk_user_role_user', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('user_role_id'),
    sa.UniqueConstraint('tenant_id', 'user_id', 'role_id', name='uq_user_role_pair')
    )
    op.create_index('ix_user_role_created_at', 'user_role', ['created_at'], unique=False)
    op.create_index('ix_user_role_tenant_role', 'user_role', ['tenant_id', 'role_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_role_tenant_role', table_name='user_role')
    op.drop_index('ix_user_role_created_at', table_name='user_role')
    op.drop_table('user_role')
    op.drop_index('ix_role_permission_tenant_permission', table_name='role_permission')
    op.drop_index('ix_role_permission_created_at', table_name='role_permission')
    op.drop_table('role_permission')
    op.drop_index('ix_role_created_at', table_name='role')
    op.drop_table('role')
    op.drop_index('ix_permission_created_at', table_name='permission')
    op.drop_table('permission')
    op.drop_index('uq_user_tenant_username', table_name='app_user')
    op.drop_index('uq_user_tenant_email', table_name='app_user')
    op.drop_index('ix_user_created_at', table_name='app_user')
    op.drop_table('app_user')
    # ### end Alembic commands ###
