"""receiving_raw_material_batch

Revision ID: 20260911_0007
Revises: 20260911_0006
Create Date: 2026-09-11 07:04:06.525443
"""
import sqlalchemy as sa

from alembic import op

revision = '20260911_0007'
down_revision = '20260911_0006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receiving',
    sa.Column('receiving_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('kitchen_id', sa.Uuid(), nullable=False),
    sa.Column('operator', sa.Uuid(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='CREATED', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('version >= 1', name='ck_receiving_version'),
    sa.ForeignKeyConstraint(['tenant_id', 'kitchen_id'], ['kitchen.tenant_id', 'kitchen.kitchen_id'], name='fk_receiving_kitchen', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'operator'], ['app_user.tenant_id', 'app_user.user_id'], name='fk_receiving_operator', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'supplier_id'], ['supplier.tenant_id', 'supplier.supplier_id'], name='fk_receiving_supplier', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('receiving_id'),
    sa.UniqueConstraint('tenant_id', 'receiving_id', 'supplier_id', name='uq_receiving_supplier'),
    sa.UniqueConstraint('tenant_id', 'receiving_id', name='uq_receiving_tenant_id')
    )
    op.create_index('ix_receiving_created_at', 'receiving', ['created_at'], unique=False)
    op.create_index('ix_receiving_received_at', 'receiving', ['received_at'], unique=False)
    op.create_index('ix_receiving_tenant_kitchen', 'receiving', ['tenant_id', 'kitchen_id'], unique=False)
    op.create_index('ix_receiving_tenant_operator', 'receiving', ['tenant_id', 'operator'], unique=False)
    op.create_index('ix_receiving_tenant_supplier', 'receiving', ['tenant_id', 'supplier_id'], unique=False)
    op.create_table('raw_material_batch',
    sa.Column('raw_material_batch_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('raw_material_id', sa.Uuid(), nullable=False),
    sa.Column('receiving_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('batch_code', sa.String(length=100), nullable=False),
    sa.Column('expired_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='CREATED', nullable=False),
    sa.Column('qr_code', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('length(trim(batch_code)) > 0', name='ck_raw_batch_code'),
    sa.CheckConstraint('qr_code IS NULL OR length(trim(qr_code)) > 0', name='ck_raw_batch_qr'),
    sa.CheckConstraint('version >= 1', name='ck_raw_batch_version'),
    sa.ForeignKeyConstraint(['tenant_id', 'raw_material_id'], ['raw_material.tenant_id', 'raw_material.raw_material_id'], name='fk_raw_batch_material', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'receiving_id', 'supplier_id'], ['receiving.tenant_id', 'receiving.receiving_id', 'receiving.supplier_id'], name='fk_raw_batch_receiving_supplier', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('raw_material_batch_id'),
    sa.UniqueConstraint('tenant_id', 'batch_code', name='uq_raw_batch_code'),
    sa.UniqueConstraint('tenant_id', 'qr_code', name='uq_raw_batch_qr'),
    sa.UniqueConstraint('tenant_id', 'raw_material_batch_id', name='uq_raw_batch_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'receiving_id', 'raw_material_batch_id', name='uq_raw_batch_receiving')
    )
    op.create_index('ix_raw_batch_created_at', 'raw_material_batch', ['created_at'], unique=False)
    op.create_index('ix_raw_batch_tenant_material', 'raw_material_batch', ['tenant_id', 'raw_material_id'], unique=False)
    op.create_table('receiving_item',
    sa.Column('receiving_item_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('receiving_id', sa.Uuid(), nullable=False),
    sa.Column('raw_material_batch_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('uom', sa.String(length=30), nullable=False),
    sa.Column('temperature', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("quantity > 0 AND quantity <> 'NaN'::numeric", name='ck_receiving_item_quantity'),
    sa.CheckConstraint("temperature IS NULL OR temperature <> 'NaN'::numeric", name='ck_receiving_item_temperature'),
    sa.CheckConstraint('length(trim(uom)) > 0', name='ck_receiving_item_uom'),
    sa.CheckConstraint('version >= 1', name='ck_receiving_item_version'),
    sa.ForeignKeyConstraint(['tenant_id', 'receiving_id', 'raw_material_batch_id'], ['raw_material_batch.tenant_id', 'raw_material_batch.receiving_id', 'raw_material_batch.raw_material_batch_id'], name='fk_receiving_item_batch', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('receiving_item_id'),
    sa.UniqueConstraint('tenant_id', 'raw_material_batch_id', name='uq_receiving_item_batch'),
    sa.UniqueConstraint('tenant_id', 'receiving_item_id', name='uq_receiving_item_tenant_id')
    )
    op.create_index('ix_receiving_item_created_at', 'receiving_item', ['created_at'], unique=False)
    op.create_index('ix_receiving_item_tenant_receiving', 'receiving_item', ['tenant_id', 'receiving_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_receiving_item_tenant_receiving', table_name='receiving_item')
    op.drop_index('ix_receiving_item_created_at', table_name='receiving_item')
    op.drop_table('receiving_item')
    op.drop_index('ix_raw_batch_tenant_material', table_name='raw_material_batch')
    op.drop_index('ix_raw_batch_created_at', table_name='raw_material_batch')
    op.drop_table('raw_material_batch')
    op.drop_index('ix_receiving_tenant_supplier', table_name='receiving')
    op.drop_index('ix_receiving_tenant_operator', table_name='receiving')
    op.drop_index('ix_receiving_tenant_kitchen', table_name='receiving')
    op.drop_index('ix_receiving_received_at', table_name='receiving')
    op.drop_index('ix_receiving_created_at', table_name='receiving')
    op.drop_table('receiving')
    # ### end Alembic commands ###
