"""packaging_alarm_holding

Revision ID: 20260911_0005
Revises: 20260911_0004
Create Date: 2026-09-11 06:55:51.134311
"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = '20260911_0005'
down_revision = '20260911_0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alarm_rule',
    sa.Column('alarm_rule_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('rule_code', sa.String(length=50), nullable=False),
    sa.Column('rule_name', sa.String(length=200), nullable=False),
    sa.Column('rule_category', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('condition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("jsonb_typeof(action) = 'object' AND action <> '{}'::jsonb", name='ck_alarm_rule_action'),
    sa.CheckConstraint("jsonb_typeof(condition) = 'object' AND condition <> '{}'::jsonb", name='ck_alarm_rule_condition'),
    sa.CheckConstraint("priority IN ('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO')", name='ck_alarm_rule_priority'),
    sa.CheckConstraint('version >= 1', name='ck_alarm_rule_version'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('alarm_rule_id'),
    sa.UniqueConstraint('tenant_id', 'alarm_rule_id', name='uq_alarm_rule_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'rule_code', name='uq_alarm_rule_tenant_code')
    )
    op.create_index('ix_alarm_rule_created_at', 'alarm_rule', ['created_at'], unique=False)
    op.create_index('ix_alarm_rule_tenant_enabled', 'alarm_rule', ['tenant_id', 'enabled'], unique=False)
    op.create_table('holding_rule',
    sa.Column('holding_rule_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('food_category', sa.String(length=100), nullable=False),
    sa.Column('maximum_minutes', sa.Integer(), nullable=False),
    sa.Column('warning_minutes', sa.Integer(), nullable=False),
    sa.Column('discard_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('discard_minutes >= maximum_minutes', name='ck_holding_rule_discard'),
    sa.CheckConstraint('maximum_minutes > 0', name='ck_holding_rule_maximum'),
    sa.CheckConstraint('version >= 1', name='ck_holding_rule_version'),
    sa.CheckConstraint('warning_minutes >= 0 AND warning_minutes <= maximum_minutes', name='ck_holding_rule_warning'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('holding_rule_id'),
    sa.UniqueConstraint('tenant_id', 'food_category', name='uq_holding_rule_tenant_category'),
    sa.UniqueConstraint('tenant_id', 'holding_rule_id', name='uq_holding_rule_tenant_id')
    )
    op.create_index('ix_holding_rule_created_at', 'holding_rule', ['created_at'], unique=False)
    op.create_table('packaging_type',
    sa.Column('package_type_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('material', sa.String(length=100), nullable=True),
    sa.Column('volume', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("volume > 0 AND volume <> 'NaN'::numeric", name='ck_packaging_volume'),
    sa.CheckConstraint('version >= 1', name='ck_packaging_version'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('package_type_id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_packaging_tenant_code'),
    sa.UniqueConstraint('tenant_id', 'package_type_id', name='uq_packaging_tenant_id')
    )
    op.create_index('ix_packaging_created_at', 'packaging_type', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_packaging_created_at', table_name='packaging_type')
    op.drop_table('packaging_type')
    op.drop_index('ix_holding_rule_created_at', table_name='holding_rule')
    op.drop_table('holding_rule')
    op.drop_index('ix_alarm_rule_tenant_enabled', table_name='alarm_rule')
    op.drop_index('ix_alarm_rule_created_at', table_name='alarm_rule')
    op.drop_table('alarm_rule')
    # ### end Alembic commands ###
