"""supplier_material_food_recipe

Revision ID: 20260911_0004
Revises: 20260911_0003
Create Date: 2026-09-11 06:52:04.756845
"""
import sqlalchemy as sa

from alembic import op

revision = '20260911_0004'
down_revision = '20260911_0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_item',
    sa.Column('food_item_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('food_code', sa.String(length=50), nullable=False),
    sa.Column('food_name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('uom', sa.String(length=30), nullable=False),
    sa.Column('holding_limit_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='ACTIVE', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('holding_limit_minutes >= 0', name='ck_food_holding_limit'),
    sa.CheckConstraint('length(trim(uom)) > 0', name='ck_food_uom'),
    sa.CheckConstraint('version >= 1', name='ck_food_version'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('food_item_id'),
    sa.UniqueConstraint('tenant_id', 'food_code', name='uq_food_tenant_code'),
    sa.UniqueConstraint('tenant_id', 'food_item_id', name='uq_food_tenant_id')
    )
    op.create_index('ix_food_created_at', 'food_item', ['created_at'], unique=False)
    op.create_table('raw_material',
    sa.Column('raw_material_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('material_code', sa.String(length=50), nullable=False),
    sa.Column('material_name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('uom', sa.String(length=30), nullable=False),
    sa.Column('storage_type', sa.String(length=50), nullable=True),
    sa.Column('recommended_temperature_min', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('recommended_temperature_max', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('maximum_storage_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='ACTIVE', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('length(trim(uom)) > 0', name='ck_material_uom'),
    sa.CheckConstraint('maximum_storage_hours >= 0', name='ck_material_storage_hours'),
    sa.CheckConstraint('recommended_temperature_min <= recommended_temperature_max', name='ck_material_temperature_range'),
    sa.CheckConstraint('version >= 1', name='ck_material_version'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('raw_material_id'),
    sa.UniqueConstraint('tenant_id', 'material_code', name='uq_material_tenant_code'),
    sa.UniqueConstraint('tenant_id', 'raw_material_id', name='uq_material_tenant_id')
    )
    op.create_index('ix_material_created_at', 'raw_material', ['created_at'], unique=False)
    op.create_table('supplier',
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_code', sa.String(length=50), nullable=False),
    sa.Column('supplier_name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='ACTIVE', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('version >= 1', name='ck_supplier_version'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('supplier_id'),
    sa.UniqueConstraint('tenant_id', 'supplier_code', name='uq_supplier_tenant_code'),
    sa.UniqueConstraint('tenant_id', 'supplier_id', name='uq_supplier_tenant_id')
    )
    op.create_index('ix_supplier_created_at', 'supplier', ['created_at'], unique=False)
    op.create_table('recipe',
    sa.Column('recipe_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('food_item_id', sa.Uuid(), nullable=False),
    sa.Column('raw_material_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('uom', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('length(trim(uom)) > 0', name='ck_recipe_uom'),
    sa.CheckConstraint('quantity > 0', name='ck_recipe_quantity'),
    sa.CheckConstraint('version >= 1', name='ck_recipe_version'),
    sa.ForeignKeyConstraint(['tenant_id', 'food_item_id'], ['food_item.tenant_id', 'food_item.food_item_id'], name='fk_recipe_tenant_food', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'raw_material_id'], ['raw_material.tenant_id', 'raw_material.raw_material_id'], name='fk_recipe_tenant_material', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('recipe_id'),
    sa.UniqueConstraint('tenant_id', 'food_item_id', 'raw_material_id', name='uq_recipe_food_material')
    )
    op.create_index('ix_recipe_created_at', 'recipe', ['created_at'], unique=False)
    op.create_index('ix_recipe_tenant_material', 'recipe', ['tenant_id', 'raw_material_id'], unique=False)
    op.create_table('supplier_material',
    sa.Column('supplier_material_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('raw_material_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('version >= 1', name='ck_supplier_material_version'),
    sa.ForeignKeyConstraint(['tenant_id', 'raw_material_id'], ['raw_material.tenant_id', 'raw_material.raw_material_id'], name='fk_supplier_material_material', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'supplier_id'], ['supplier.tenant_id', 'supplier.supplier_id'], name='fk_supplier_material_supplier', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('supplier_material_id'),
    sa.UniqueConstraint('tenant_id', 'supplier_id', 'raw_material_id', name='uq_supplier_material_pair')
    )
    op.create_index('ix_supplier_material_created_at', 'supplier_material', ['created_at'], unique=False)
    op.create_index('ix_supplier_material_tenant_material', 'supplier_material', ['tenant_id', 'raw_material_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_supplier_material_tenant_material', table_name='supplier_material')
    op.drop_index('ix_supplier_material_created_at', table_name='supplier_material')
    op.drop_table('supplier_material')
    op.drop_index('ix_recipe_tenant_material', table_name='recipe')
    op.drop_index('ix_recipe_created_at', table_name='recipe')
    op.drop_table('recipe')
    op.drop_index('ix_supplier_created_at', table_name='supplier')
    op.drop_table('supplier')
    op.drop_index('ix_material_created_at', table_name='raw_material')
    op.drop_table('raw_material')
    op.drop_index('ix_food_created_at', table_name='food_item')
    op.drop_table('food_item')
    # ### end Alembic commands ###
