"""stock_putaway_ledger

Revision ID: 20260911_0018
Revises: 20260911_0017
Create Date: 2026-09-11 21:31:02.851210
"""
import sqlalchemy as sa

from alembic import op

revision = '20260911_0018'
down_revision = '20260911_0017'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_entry',
    sa.Column('stock_entry_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('raw_material_batch_id', sa.Uuid(), nullable=False),
    sa.Column('storage_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('batch_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("quantity > 0 AND quantity <> 'NaN'::numeric", name='ck_stock_quantity'),
    sa.CheckConstraint('batch_version >= 1', name='ck_stock_batch_version'),
    sa.CheckConstraint('deleted_at IS NULL AND deleted_by IS NULL', name='ck_stock_not_deleted'),
    sa.ForeignKeyConstraint(['tenant_id', 'raw_material_batch_id'], ['raw_material_batch.tenant_id', 'raw_material_batch.raw_material_batch_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'storage_id'], ['storage.tenant_id', 'storage.storage_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('stock_entry_id'),
    sa.UniqueConstraint('tenant_id', 'raw_material_batch_id', 'batch_version', name='uq_stock_batch_version')
    )
    op.create_index('ix_stock_storage', 'stock_entry', ['tenant_id', 'storage_id'], unique=False)
    # ### end Alembic commands ###

    op.execute("CREATE TRIGGER stock_entry_immutable BEFORE UPDATE OR DELETE ON stock_entry FOR EACH ROW EXECUTE FUNCTION public.fsos_reject_event_mutation()")
    op.execute("CREATE TRIGGER stock_entry_no_truncate BEFORE TRUNCATE ON stock_entry FOR EACH STATEMENT EXECUTE FUNCTION public.fsos_reject_event_mutation()")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stock_storage', table_name='stock_entry')
    op.drop_table('stock_entry')
    # ### end Alembic commands ###
