"""delivery_school_receiving

Revision ID: 20260911_0009
Revises: 20260911_0008
Create Date: 2026-09-11 07:14:49.640735
"""
import sqlalchemy as sa

from alembic import op

revision = '20260911_0009'
down_revision = '20260911_0008'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery',
    sa.Column('delivery_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle', sa.Uuid(), nullable=False),
    sa.Column('driver', sa.Uuid(), nullable=False),
    sa.Column('departure_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrival_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='CREATED', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('arrival_time IS NULL OR (departure_time IS NOT NULL AND arrival_time >= departure_time)', name='ck_delivery_time_order'),
    sa.CheckConstraint('version >= 1', name='ck_delivery_version'),
    sa.ForeignKeyConstraint(['tenant_id', 'driver'], ['driver.tenant_id', 'driver.driver_id'], name='fk_delivery_driver', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'vehicle'], ['vehicle.tenant_id', 'vehicle.vehicle_id'], name='fk_delivery_vehicle', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('delivery_id'),
    sa.UniqueConstraint('tenant_id', 'delivery_id', name='uq_delivery_tenant_id')
    )
    op.create_index('ix_delivery_created_at', 'delivery', ['created_at'], unique=False)
    op.create_index('ix_delivery_departure_time', 'delivery', ['departure_time'], unique=False)
    op.create_index('ix_delivery_tenant_driver', 'delivery', ['tenant_id', 'driver'], unique=False)
    op.create_index('ix_delivery_tenant_vehicle', 'delivery', ['tenant_id', 'vehicle'], unique=False)
    op.create_table('delivery_item',
    sa.Column('delivery_item_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('delivery_id', sa.Uuid(), nullable=False),
    sa.Column('package_id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('version >= 1', name='ck_delivery_item_version'),
    sa.ForeignKeyConstraint(['tenant_id', 'delivery_id'], ['delivery.tenant_id', 'delivery.delivery_id'], name='fk_delivery_item_delivery', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'package_id'], ['package.tenant_id', 'package.package_id'], name='fk_delivery_item_package', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'school_id'], ['school.tenant_id', 'school.school_id'], name='fk_delivery_item_school', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('delivery_item_id'),
    sa.UniqueConstraint('tenant_id', 'delivery_id', 'package_id', 'school_id', name='uq_delivery_item_destination'),
    sa.UniqueConstraint('tenant_id', 'delivery_id', 'package_id', name='uq_delivery_item_package'),
    sa.UniqueConstraint('tenant_id', 'delivery_item_id', name='uq_delivery_item_tenant_id')
    )
    op.create_index('ix_delivery_item_created_at', 'delivery_item', ['created_at'], unique=False)
    op.create_index('ix_delivery_item_tenant_package', 'delivery_item', ['tenant_id', 'package_id'], unique=False)
    op.create_index('ix_delivery_item_tenant_school', 'delivery_item', ['tenant_id', 'school_id'], unique=False)
    op.create_table('school_receiving',
    sa.Column('school_receiving_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('delivery_id', sa.Uuid(), nullable=False),
    sa.Column('school', sa.Uuid(), nullable=False),
    sa.Column('package', sa.Uuid(), nullable=False),
    sa.Column('received_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.Column('photo', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("temperature IS NULL OR temperature <> 'NaN'::numeric", name='ck_school_receiving_temperature'),
    sa.CheckConstraint('version >= 1', name='ck_school_receiving_version'),
    sa.ForeignKeyConstraint(['tenant_id', 'delivery_id', 'package', 'school'], ['delivery_item.tenant_id', 'delivery_item.delivery_id', 'delivery_item.package_id', 'delivery_item.school_id'], name='fk_school_receiving_destination', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('school_receiving_id'),
    sa.UniqueConstraint('tenant_id', 'delivery_id', 'package', name='uq_school_receiving_package'),
    sa.UniqueConstraint('tenant_id', 'school_receiving_id', name='uq_school_receiving_tenant_id')
    )
    op.create_index('ix_school_receiving_created_at', 'school_receiving', ['created_at'], unique=False)
    op.create_index('ix_school_receiving_received_time', 'school_receiving', ['received_time'], unique=False)
    op.create_index('ix_school_receiving_tenant_package', 'school_receiving', ['tenant_id', 'package'], unique=False)
    op.create_index('ix_school_receiving_tenant_school', 'school_receiving', ['tenant_id', 'school'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_school_receiving_tenant_school', table_name='school_receiving')
    op.drop_index('ix_school_receiving_tenant_package', table_name='school_receiving')
    op.drop_index('ix_school_receiving_received_time', table_name='school_receiving')
    op.drop_index('ix_school_receiving_created_at', table_name='school_receiving')
    op.drop_table('school_receiving')
    op.drop_index('ix_delivery_item_tenant_school', table_name='delivery_item')
    op.drop_index('ix_delivery_item_tenant_package', table_name='delivery_item')
    op.drop_index('ix_delivery_item_created_at', table_name='delivery_item')
    op.drop_table('delivery_item')
    op.drop_index('ix_delivery_tenant_vehicle', table_name='delivery')
    op.drop_index('ix_delivery_tenant_driver', table_name='delivery')
    op.drop_index('ix_delivery_departure_time', table_name='delivery')
    op.drop_index('ix_delivery_created_at', table_name='delivery')
    op.drop_table('delivery')
    # ### end Alembic commands ###
