"""rule_revision_history

Revision ID: 20260911_0015
Revises: 20260911_0014
Create Date: 2026-09-11 09:18:16.777393
"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = '20260911_0015'
down_revision = '20260911_0014'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alarm_rule_revision',
    sa.Column('revision_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("jsonb_typeof(snapshot) = 'object'", name='ck_alarm_revision_snapshot'),
    sa.CheckConstraint('version >= 1', name='ck_alarm_revision_version'),
    sa.ForeignKeyConstraint(['tenant_id', 'rule_id'], ['alarm_rule.tenant_id', 'alarm_rule.alarm_rule_id'], name='fk_alarm_revision_rule', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('revision_id'),
    sa.UniqueConstraint('tenant_id', 'rule_id', 'version', name='uq_alarm_revision_version')
    )
    op.create_table('holding_rule_revision',
    sa.Column('revision_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("jsonb_typeof(snapshot) = 'object'", name='ck_holding_revision_snapshot'),
    sa.CheckConstraint('version >= 1', name='ck_holding_revision_version'),
    sa.ForeignKeyConstraint(['tenant_id', 'rule_id'], ['holding_rule.tenant_id', 'holding_rule.holding_rule_id'], name='fk_holding_revision_rule', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('revision_id'),
    sa.UniqueConstraint('tenant_id', 'rule_id', 'version', name='uq_holding_revision_version')
    )
    op.execute("""
        CREATE FUNCTION public.fsos_rule_history_guard() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          RAISE EXCEPTION 'Rule history cannot be removed or modified' USING ERRCODE='55000';
        END $$
    """)
    op.execute("""
        CREATE FUNCTION public.fsos_rule_version() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          IF NEW.tenant_id IS DISTINCT FROM OLD.tenant_id
             OR to_jsonb(NEW)->TG_ARGV[0] IS DISTINCT FROM to_jsonb(OLD)->TG_ARGV[0]
             OR NEW.created_at IS DISTINCT FROM OLD.created_at
             OR NEW.created_by IS DISTINCT FROM OLD.created_by THEN
            RAISE EXCEPTION 'Rule identity and creation audit are immutable' USING ERRCODE='23514';
          END IF;
          IF NEW.version NOT IN (OLD.version, OLD.version + 1) OR NEW.version IS NULL THEN
            RAISE EXCEPTION 'Invalid rule version' USING ERRCODE='23514';
          END IF;
          NEW.version := OLD.version + 1;
          NEW.updated_at := clock_timestamp();
          RETURN NEW;
        END $$
    """)
    op.execute("""
        CREATE FUNCTION public.fsos_capture_rule_revision() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          EXECUTE format('INSERT INTO public.%I (revision_id, tenant_id, rule_id, version, snapshot) '
                         'VALUES (gen_random_uuid(), $1, $2, $3, $4)', TG_ARGV[1])
            USING NEW.tenant_id, (to_jsonb(NEW)->>TG_ARGV[0])::uuid, NEW.version, to_jsonb(NEW);
          RETURN NEW;
        END $$
    """)
    for kind in ('alarm', 'holding'):
        parent, history, pk = f'{kind}_rule', f'{kind}_rule_revision', f'{kind}_rule_id'
        # Lock out concurrent writes while installing the baseline and capture triggers.
        op.execute(f'LOCK TABLE public.{parent} IN ACCESS EXCLUSIVE MODE')
        op.execute(f'INSERT INTO public.{history} (revision_id, tenant_id, rule_id, version, snapshot) '
                   f'SELECT gen_random_uuid(), tenant_id, {pk}, version, to_jsonb(r) FROM public.{parent} r')
        op.execute(f"CREATE TRIGGER rule_version BEFORE UPDATE ON public.{parent} FOR EACH ROW "
                   f"EXECUTE FUNCTION public.fsos_rule_version('{pk}')")
        op.execute(f"CREATE TRIGGER rule_capture AFTER INSERT OR UPDATE ON public.{parent} FOR EACH ROW "
                   f"EXECUTE FUNCTION public.fsos_capture_rule_revision('{pk}', '{history}')")
        op.execute(f'CREATE TRIGGER rule_no_delete BEFORE DELETE ON public.{parent} FOR EACH ROW '
                   'EXECUTE FUNCTION public.fsos_rule_history_guard()')
        op.execute(f'CREATE TRIGGER revision_immutable BEFORE UPDATE OR DELETE ON public.{history} FOR EACH ROW '
                   'EXECUTE FUNCTION public.fsos_rule_history_guard()')
        for table in (parent, history):
            op.execute(f'CREATE TRIGGER rule_no_truncate BEFORE TRUNCATE ON public.{table} FOR EACH STATEMENT '
                       'EXECUTE FUNCTION public.fsos_rule_history_guard()')


def downgrade() -> None:
    for table in ('alarm_rule', 'holding_rule'):
        for trigger in ('rule_version', 'rule_capture', 'rule_no_delete', 'rule_no_truncate'):
            op.execute(f'DROP TRIGGER {trigger} ON public.{table}')
    op.drop_table('holding_rule_revision')
    op.drop_table('alarm_rule_revision')
    op.execute('DROP FUNCTION public.fsos_capture_rule_revision()')
    op.execute('DROP FUNCTION public.fsos_rule_version()')
    op.execute('DROP FUNCTION public.fsos_rule_history_guard()')
