"""delivery_workflow

Revision ID: 20260911_0021
Revises: 20260911_0020
Create Date: 2026-09-11 22:03:17.087678
"""
import sqlalchemy as sa

from alembic import op

revision = '20260911_0021'
down_revision = '20260911_0020'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery', sa.Column('kitchen_id', sa.Uuid(), nullable=True))
    op.add_column('delivery', sa.Column('estimated_arrival_time', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key('fk_delivery_kitchen', 'delivery', 'kitchen', ['tenant_id', 'kitchen_id'], ['tenant_id', 'kitchen_id'], ondelete='RESTRICT')
    op.create_check_constraint('ck_delivery_eta', 'delivery', 'estimated_arrival_time IS NULL OR (departure_time IS NOT NULL AND estimated_arrival_time > departure_time)')
    op.execute('CREATE TRIGGER delivery_item_immutable BEFORE UPDATE OR DELETE ON delivery_item FOR EACH ROW EXECUTE FUNCTION public.fsos_reject_event_mutation()')
    op.execute('CREATE TRIGGER delivery_item_no_truncate BEFORE TRUNCATE ON delivery_item FOR EACH STATEMENT EXECUTE FUNCTION public.fsos_reject_event_mutation()')
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute('DROP TRIGGER delivery_item_immutable ON delivery_item')
    op.execute('DROP TRIGGER delivery_item_no_truncate ON delivery_item')
    op.drop_constraint('ck_delivery_eta', 'delivery', type_='check')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_delivery_kitchen', 'delivery', type_='foreignkey')
    op.drop_column('delivery', 'estimated_arrival_time')
    op.drop_column('delivery', 'kitchen_id')
    # ### end Alembic commands ###
