"""production_package

Revision ID: 20260911_0008
Revises: 20260911_0007
Create Date: 2026-09-11 07:09:37.090706
"""
import sqlalchemy as sa

from alembic import op

revision = '20260911_0008'
down_revision = '20260911_0007'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_batch',
    sa.Column('production_batch_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('batch_code', sa.String(length=100), nullable=False),
    sa.Column('kitchen', sa.Uuid(), nullable=False),
    sa.Column('menu', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('holding_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('holding_expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='CREATED', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('finished_at IS NULL OR (started_at IS NOT NULL AND finished_at >= started_at)', name='ck_production_time_order'),
    sa.CheckConstraint('holding_expired_at IS NULL OR (holding_started_at IS NOT NULL AND holding_expired_at >= holding_started_at)', name='ck_production_holding_order'),
    sa.CheckConstraint('length(trim(batch_code)) > 0', name='ck_production_batch_code'),
    sa.CheckConstraint('version >= 1', name='ck_production_version'),
    sa.ForeignKeyConstraint(['tenant_id', 'kitchen'], ['kitchen.tenant_id', 'kitchen.kitchen_id'], name='fk_production_kitchen', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'menu'], ['food_item.tenant_id', 'food_item.food_item_id'], name='fk_production_menu', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('production_batch_id'),
    sa.UniqueConstraint('tenant_id', 'batch_code', name='uq_production_batch_code'),
    sa.UniqueConstraint('tenant_id', 'production_batch_id', name='uq_production_tenant_id')
    )
    op.create_index('ix_production_created_at', 'production_batch', ['created_at'], unique=False)
    op.create_index('ix_production_tenant_kitchen', 'production_batch', ['tenant_id', 'kitchen'], unique=False)
    op.create_index('ix_production_tenant_menu', 'production_batch', ['tenant_id', 'menu'], unique=False)
    op.create_table('package',
    sa.Column('package_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('package_code', sa.String(length=100), nullable=False),
    sa.Column('production_batch_id', sa.Uuid(), nullable=False),
    sa.Column('package_type_id', sa.Uuid(), nullable=True),
    sa.Column('package_number', sa.Integer(), nullable=False),
    sa.Column('remaining_minutes', sa.Integer(), nullable=True),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='CREATED', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('length(trim(package_code)) > 0', name='ck_package_code'),
    sa.CheckConstraint('package_number > 0', name='ck_package_number'),
    sa.CheckConstraint('version >= 1', name='ck_package_version'),
    sa.ForeignKeyConstraint(['tenant_id', 'package_type_id'], ['packaging_type.tenant_id', 'packaging_type.package_type_id'], name='fk_package_type', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'production_batch_id'], ['production_batch.tenant_id', 'production_batch.production_batch_id'], name='fk_package_production', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('package_id'),
    sa.UniqueConstraint('tenant_id', 'package_code', name='uq_package_code'),
    sa.UniqueConstraint('tenant_id', 'package_id', name='uq_package_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'production_batch_id', 'package_number', name='uq_package_batch_number')
    )
    op.create_index('ix_package_created_at', 'package', ['created_at'], unique=False)
    op.create_index('ix_package_expired_at', 'package', ['expired_at'], unique=False)
    op.create_index('ix_package_tenant_type', 'package', ['tenant_id', 'package_type_id'], unique=False)
    op.create_table('production_item',
    sa.Column('production_item_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('production_batch_id', sa.Uuid(), nullable=False),
    sa.Column('raw_material_batch_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('uom', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("quantity > 0 AND quantity <> 'NaN'::numeric", name='ck_production_item_quantity'),
    sa.CheckConstraint('length(trim(uom)) > 0', name='ck_production_item_uom'),
    sa.CheckConstraint('version >= 1', name='ck_production_item_version'),
    sa.ForeignKeyConstraint(['tenant_id', 'production_batch_id'], ['production_batch.tenant_id', 'production_batch.production_batch_id'], name='fk_production_item_batch', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'raw_material_batch_id'], ['raw_material_batch.tenant_id', 'raw_material_batch.raw_material_batch_id'], name='fk_production_item_material', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('production_item_id'),
    sa.UniqueConstraint('tenant_id', 'production_batch_id', 'raw_material_batch_id', name='uq_production_item_material'),
    sa.UniqueConstraint('tenant_id', 'production_item_id', name='uq_production_item_tenant_id')
    )
    op.create_index('ix_production_item_created_at', 'production_item', ['created_at'], unique=False)
    op.create_index('ix_production_item_tenant_material', 'production_item', ['tenant_id', 'raw_material_batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_production_item_tenant_material', table_name='production_item')
    op.drop_index('ix_production_item_created_at', table_name='production_item')
    op.drop_table('production_item')
    op.drop_index('ix_package_tenant_type', table_name='package')
    op.drop_index('ix_package_expired_at', table_name='package')
    op.drop_index('ix_package_created_at', table_name='package')
    op.drop_table('package')
    op.drop_index('ix_production_tenant_menu', table_name='production_batch')
    op.drop_index('ix_production_tenant_kitchen', table_name='production_batch')
    op.drop_index('ix_production_created_at', table_name='production_batch')
    op.drop_table('production_batch')
    # ### end Alembic commands ###
