"""remaining_telemetry

Revision ID: 20260911_0014
Revises: 20260911_0013
Create Date: 2026-09-11 08:43:27.255031
"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = '20260911_0014'
down_revision = '20260911_0013'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holding_log',
    sa.Column('holding_id', sa.Uuid(), nullable=False),
    sa.Column('package_uuid', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('elapsed_minutes', sa.Integer(), nullable=False),
    sa.Column('remaining_minutes', sa.Integer(), nullable=False),
    sa.Column('warning_level', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mqtt_message_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('deleted_at IS NULL AND deleted_by IS NULL', name='ck_holding_not_deleted'),
    sa.CheckConstraint('elapsed_minutes >= 0', name='ck_holding_elapsed'),
    sa.CheckConstraint('length(trim(status)) > 0', name='ck_holding_status'),
    sa.CheckConstraint('length(trim(warning_level)) > 0', name='ck_holding_warning'),
    sa.CheckConstraint('version >= 1', name='ck_holding_version'),
    sa.ForeignKeyConstraint(['tenant_id', 'mqtt_message_id'], ['mqtt_message_log.tenant_id', 'mqtt_message_log.message_uuid'], name='fk_holding_mqtt', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'package_uuid'], ['package.tenant_id', 'package.package_id'], name='fk_holding_package', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('holding_id')
    )
    op.create_index('ix_holding_mqtt', 'holding_log', ['tenant_id', 'mqtt_message_id'], unique=False)
    op.create_index('ix_holding_package_time', 'holding_log', ['tenant_id', 'package_uuid', 'recorded_at'], unique=False)
    op.create_index('ix_holding_recorded', 'holding_log', ['recorded_at'], unique=False)
    op.create_table('alarm_log',
    sa.Column('alarm_id', sa.Uuid(), nullable=False),
    sa.Column('device_uuid', sa.Uuid(), nullable=False),
    sa.Column('alarm_code', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mqtt_message_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('deleted_at IS NULL AND deleted_by IS NULL', name='ck_alarm_not_deleted'),
    sa.CheckConstraint('length(trim(alarm_code)) > 0', name='ck_alarm_code'),
    sa.CheckConstraint('length(trim(severity)) > 0', name='ck_alarm_severity'),
    sa.CheckConstraint('version >= 1', name='ck_alarm_version'),
    sa.ForeignKeyConstraint(['tenant_id', 'device_uuid'], ['device.tenant_id', 'device.device_uuid'], name='fk_alarm_device', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'mqtt_message_id'], ['mqtt_message_log.tenant_id', 'mqtt_message_log.message_uuid'], name='fk_alarm_mqtt', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('alarm_id'),
    sa.UniqueConstraint('tenant_id', 'alarm_id', name='uq_alarm_tenant_id')
    )
    op.create_index('ix_alarm_device_time', 'alarm_log', ['tenant_id', 'device_uuid', 'recorded_at'], unique=False)
    op.create_index('ix_alarm_mqtt', 'alarm_log', ['tenant_id', 'mqtt_message_id'], unique=False)
    op.create_index('ix_alarm_recorded', 'alarm_log', ['recorded_at'], unique=False)
    op.create_table('battery_log',
    sa.Column('battery_log_id', sa.Uuid(), nullable=False),
    sa.Column('device_uuid', sa.Uuid(), nullable=False),
    sa.Column('battery', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('voltage', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('charging', sa.Boolean(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mqtt_message_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("voltage >= 0 AND voltage <> 'NaN'::numeric", name='ck_battery_voltage'),
    sa.CheckConstraint('battery BETWEEN 0 AND 100', name='ck_battery_level'),
    sa.CheckConstraint('battery IS NOT NULL OR voltage IS NOT NULL OR percentage IS NOT NULL OR charging IS NOT NULL', name='ck_battery_measurement'),
    sa.CheckConstraint('deleted_at IS NULL AND deleted_by IS NULL', name='ck_battery_not_deleted'),
    sa.CheckConstraint('percentage BETWEEN 0 AND 100', name='ck_battery_percentage'),
    sa.CheckConstraint('version >= 1', name='ck_battery_version'),
    sa.ForeignKeyConstraint(['tenant_id', 'device_uuid'], ['device.tenant_id', 'device.device_uuid'], name='fk_battery_device', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'mqtt_message_id'], ['mqtt_message_log.tenant_id', 'mqtt_message_log.message_uuid'], name='fk_battery_mqtt', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('battery_log_id')
    )
    op.create_index('ix_battery_device_time', 'battery_log', ['tenant_id', 'device_uuid', 'recorded_at'], unique=False)
    op.create_index('ix_battery_mqtt', 'battery_log', ['tenant_id', 'mqtt_message_id'], unique=False)
    op.create_index('ix_battery_recorded', 'battery_log', ['recorded_at'], unique=False)
    op.create_table('device_health_log',
    sa.Column('device_health_log_id', sa.Uuid(), nullable=False),
    sa.Column('device_uuid', sa.Uuid(), nullable=False),
    sa.Column('health', sa.String(length=50), nullable=False),
    sa.Column('sensor', sa.String(length=50), nullable=True),
    sa.Column('wifi', sa.String(length=50), nullable=True),
    sa.Column('mqtt', sa.String(length=50), nullable=True),
    sa.Column('gps', sa.String(length=50), nullable=True),
    sa.Column('battery', sa.String(length=50), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mqtt_message_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('deleted_at IS NULL AND deleted_by IS NULL', name='ck_device_health_not_deleted'),
    sa.CheckConstraint('length(trim(health)) > 0', name='ck_device_health_status'),
    sa.CheckConstraint('version >= 1', name='ck_device_health_version'),
    sa.ForeignKeyConstraint(['tenant_id', 'device_uuid'], ['device.tenant_id', 'device.device_uuid'], name='fk_device_health_device', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'mqtt_message_id'], ['mqtt_message_log.tenant_id', 'mqtt_message_log.message_uuid'], name='fk_device_health_mqtt', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('device_health_log_id')
    )
    op.create_index('ix_device_health_device_time', 'device_health_log', ['tenant_id', 'device_uuid', 'recorded_at'], unique=False)
    op.create_index('ix_device_health_mqtt', 'device_health_log', ['tenant_id', 'mqtt_message_id'], unique=False)
    op.create_index('ix_device_health_recorded', 'device_health_log', ['recorded_at'], unique=False)
    op.create_table('device_session',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('device_uuid', sa.Uuid(), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disconnected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('firmware', sa.String(length=100), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mqtt_message_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('deleted_at IS NULL AND deleted_by IS NULL', name='ck_device_session_not_deleted'),
    sa.CheckConstraint('disconnected_at >= connected_at', name='ck_device_session_time'),
    sa.CheckConstraint('version >= 1', name='ck_device_session_version'),
    sa.ForeignKeyConstraint(['tenant_id', 'device_uuid'], ['device.tenant_id', 'device.device_uuid'], name='fk_device_session_device', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'mqtt_message_id'], ['mqtt_message_log.tenant_id', 'mqtt_message_log.message_uuid'], name='fk_device_session_mqtt', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('session_id'),
    sa.UniqueConstraint('tenant_id', 'session_id', name='uq_device_session_tenant_id')
    )
    op.create_index('ix_device_session_connected', 'device_session', ['tenant_id', 'device_uuid', 'connected_at'], unique=False)
    op.create_index('ix_device_session_device_time', 'device_session', ['tenant_id', 'device_uuid', 'recorded_at'], unique=False)
    op.create_index('ix_device_session_mqtt', 'device_session', ['tenant_id', 'mqtt_message_id'], unique=False)
    op.create_index('ix_device_session_recorded', 'device_session', ['recorded_at'], unique=False)
    op.create_table('signal_log',
    sa.Column('signal_log_id', sa.Uuid(), nullable=False),
    sa.Column('device_uuid', sa.Uuid(), nullable=False),
    sa.Column('wifi_signal', sa.Integer(), nullable=True),
    sa.Column('rssi', sa.Integer(), nullable=True),
    sa.Column('quality', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mqtt_message_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('deleted_at IS NULL AND deleted_by IS NULL', name='ck_signal_not_deleted'),
    sa.CheckConstraint('quality BETWEEN 0 AND 100', name='ck_signal_quality'),
    sa.CheckConstraint('version >= 1', name='ck_signal_version'),
    sa.CheckConstraint('wifi_signal IS NOT NULL OR rssi IS NOT NULL OR quality IS NOT NULL', name='ck_signal_measurement'),
    sa.ForeignKeyConstraint(['tenant_id', 'device_uuid'], ['device.tenant_id', 'device.device_uuid'], name='fk_signal_device', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'mqtt_message_id'], ['mqtt_message_log.tenant_id', 'mqtt_message_log.message_uuid'], name='fk_signal_mqtt', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('signal_log_id')
    )
    op.create_index('ix_signal_device_time', 'signal_log', ['tenant_id', 'device_uuid', 'recorded_at'], unique=False)
    op.create_index('ix_signal_mqtt', 'signal_log', ['tenant_id', 'mqtt_message_id'], unique=False)
    op.create_index('ix_signal_recorded', 'signal_log', ['recorded_at'], unique=False)
    op.create_table('alarm_acknowledgment',
    sa.Column('acknowledgment_id', sa.Uuid(), nullable=False),
    sa.Column('alarm_id', sa.Uuid(), nullable=False),
    sa.Column('acknowledged_by', sa.Uuid(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mqtt_message_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('deleted_at IS NULL AND deleted_by IS NULL', name='ck_alarm_ack_not_deleted'),
    sa.CheckConstraint('version >= 1', name='ck_alarm_ack_version'),
    sa.ForeignKeyConstraint(['tenant_id', 'acknowledged_by'], ['app_user.tenant_id', 'app_user.user_id'], name='fk_alarm_ack_actor', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'alarm_id'], ['alarm_log.tenant_id', 'alarm_log.alarm_id'], name='fk_alarm_ack_alarm', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'mqtt_message_id'], ['mqtt_message_log.tenant_id', 'mqtt_message_log.message_uuid'], name='fk_alarm_ack_mqtt', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('acknowledgment_id'),
    sa.UniqueConstraint('tenant_id', 'alarm_id', name='uq_alarm_ack_once')
    )
    op.create_index('ix_alarm_ack_mqtt', 'alarm_acknowledgment', ['tenant_id', 'mqtt_message_id'], unique=False)
    op.create_index('ix_alarm_ack_recorded', 'alarm_acknowledgment', ['recorded_at'], unique=False)
    op.create_table('device_session_end',
    sa.Column('session_end_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('disconnected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mqtt_message_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('deleted_at IS NULL AND deleted_by IS NULL', name='ck_session_end_not_deleted'),
    sa.CheckConstraint('version >= 1', name='ck_session_end_version'),
    sa.ForeignKeyConstraint(['tenant_id', 'mqtt_message_id'], ['mqtt_message_log.tenant_id', 'mqtt_message_log.message_uuid'], name='fk_session_end_mqtt', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'session_id'], ['device_session.tenant_id', 'device_session.session_id'], name='fk_session_end_session', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('session_end_id'),
    sa.UniqueConstraint('tenant_id', 'session_id', name='uq_session_end_once')
    )
    op.create_index('ix_session_end_mqtt', 'device_session_end', ['tenant_id', 'mqtt_message_id'], unique=False)
    op.create_index('ix_session_end_recorded', 'device_session_end', ['recorded_at'], unique=False)
    for table in ('device_health_log', 'alarm_log', 'holding_log', 'signal_log',
                  'battery_log', 'device_session', 'alarm_acknowledgment', 'device_session_end'):
        op.execute(f'CREATE TRIGGER telemetry_immutable BEFORE UPDATE OR DELETE ON public.{table} '
                   'FOR EACH ROW EXECUTE FUNCTION public.fsos_reject_telemetry_mutation()')
        op.execute(f'CREATE TRIGGER telemetry_no_truncate BEFORE TRUNCATE ON public.{table} '
                   'FOR EACH STATEMENT EXECUTE FUNCTION public.fsos_reject_telemetry_mutation()')
    # Parents are immutable; the unique constraints serialize competing finalizations.
    op.execute("""
        CREATE FUNCTION public.fsos_validate_telemetry_completion() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
          IF TG_TABLE_NAME = 'alarm_acknowledgment' THEN
            IF NOT EXISTS (SELECT 1 FROM public.alarm_log a
                WHERE a.tenant_id=NEW.tenant_id AND a.alarm_id=NEW.alarm_id
                  AND NOT a.acknowledged AND NEW.acknowledged_at >= a.recorded_at) THEN
              RAISE EXCEPTION 'Alarm must exist, be unacknowledged and precede acknowledgment'
                USING ERRCODE='23514';
            END IF;
          ELSE
            IF NOT EXISTS (SELECT 1 FROM public.device_session s
                WHERE s.tenant_id=NEW.tenant_id AND s.session_id=NEW.session_id
                  AND s.disconnected_at IS NULL AND NEW.disconnected_at >= s.connected_at) THEN
              RAISE EXCEPTION 'Session must exist, be open and precede disconnection'
                USING ERRCODE='23514';
            END IF;
          END IF;
          RETURN NEW;
        END $$
    """)
    for table in ('alarm_acknowledgment', 'device_session_end'):
        op.execute(f'CREATE TRIGGER telemetry_completion BEFORE INSERT ON public.{table} '
                   'FOR EACH ROW EXECUTE FUNCTION public.fsos_validate_telemetry_completion()')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_session_end_recorded', table_name='device_session_end')
    op.drop_index('ix_session_end_mqtt', table_name='device_session_end')
    op.drop_table('device_session_end')
    op.drop_index('ix_alarm_ack_recorded', table_name='alarm_acknowledgment')
    op.drop_index('ix_alarm_ack_mqtt', table_name='alarm_acknowledgment')
    op.drop_table('alarm_acknowledgment')
    op.drop_index('ix_signal_recorded', table_name='signal_log')
    op.drop_index('ix_signal_mqtt', table_name='signal_log')
    op.drop_index('ix_signal_device_time', table_name='signal_log')
    op.drop_table('signal_log')
    op.drop_index('ix_device_session_recorded', table_name='device_session')
    op.drop_index('ix_device_session_mqtt', table_name='device_session')
    op.drop_index('ix_device_session_device_time', table_name='device_session')
    op.drop_index('ix_device_session_connected', table_name='device_session')
    op.drop_table('device_session')
    op.drop_index('ix_device_health_recorded', table_name='device_health_log')
    op.drop_index('ix_device_health_mqtt', table_name='device_health_log')
    op.drop_index('ix_device_health_device_time', table_name='device_health_log')
    op.drop_table('device_health_log')
    op.drop_index('ix_battery_recorded', table_name='battery_log')
    op.drop_index('ix_battery_mqtt', table_name='battery_log')
    op.drop_index('ix_battery_device_time', table_name='battery_log')
    op.drop_table('battery_log')
    op.drop_index('ix_alarm_recorded', table_name='alarm_log')
    op.drop_index('ix_alarm_mqtt', table_name='alarm_log')
    op.drop_index('ix_alarm_device_time', table_name='alarm_log')
    op.drop_table('alarm_log')
    op.drop_index('ix_holding_recorded', table_name='holding_log')
    op.drop_index('ix_holding_package_time', table_name='holding_log')
    op.drop_index('ix_holding_mqtt', table_name='holding_log')
    op.drop_table('holding_log')
    op.execute('DROP FUNCTION public.fsos_validate_telemetry_completion()')
