"""vehicle_driver_school

Revision ID: 20260911_0003
Revises: 20260911_0002
Create Date: 2026-09-11 06:47:03.055652
"""
import geoalchemy2
import sqlalchemy as sa

from alembic import op

revision = '20260911_0003'
down_revision = '20260911_0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver',
    sa.Column('driver_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('driver_code', sa.String(length=50), nullable=False),
    sa.Column('driver_name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='ACTIVE', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('version >= 1', name='ck_driver_version'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('driver_id'),
    sa.UniqueConstraint('tenant_id', 'driver_code', name='uq_driver_tenant_code'),
    sa.UniqueConstraint('tenant_id', 'driver_id', name='uq_driver_tenant_id')
    )
    op.create_index('ix_driver_created_at', 'driver', ['created_at'], unique=False)
    op.create_table('school',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('kitchen_id', sa.Uuid(), nullable=False),
    sa.Column('school_code', sa.String(length=50), nullable=False),
    sa.Column('school_name', sa.String(length=200), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), sa.Computed('CASE WHEN latitude IS NULL OR longitude IS NULL THEN NULL ELSE ST_SetSRID(ST_MakePoint(longitude::double precision, latitude::double precision), 4326) END', persisted=True), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('student_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='ACTIVE', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('(latitude IS NULL) = (longitude IS NULL)', name='ck_school_coordinate_pair'),
    sa.CheckConstraint('latitude BETWEEN -90 AND 90', name='ck_school_latitude'),
    sa.CheckConstraint('longitude BETWEEN -180 AND 180', name='ck_school_longitude'),
    sa.CheckConstraint('student_count >= 0', name='ck_school_student_count'),
    sa.CheckConstraint('version >= 1', name='ck_school_version'),
    sa.ForeignKeyConstraint(['tenant_id', 'kitchen_id'], ['kitchen.tenant_id', 'kitchen.kitchen_id'], name='fk_school_tenant_kitchen', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('school_id'),
    sa.UniqueConstraint('tenant_id', 'school_code', name='uq_school_tenant_code'),
    sa.UniqueConstraint('tenant_id', 'school_id', name='uq_school_tenant_id')
    )
    op.create_index('ix_school_created_at', 'school', ['created_at'], unique=False)
    op.create_index('ix_school_location', 'school', ['location'], unique=False, postgresql_using='gist')
    op.create_index('ix_school_tenant_kitchen', 'school', ['tenant_id', 'kitchen_id'], unique=False)
    op.create_table('vehicle',
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_code', sa.String(length=50), nullable=False),
    sa.Column('plate_number', sa.String(length=30), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=False),
    sa.Column('capacity', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('gps_device', sa.Uuid(), nullable=True),
    sa.Column('driver_id', sa.Uuid(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='ACTIVE', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('capacity >= 0', name='ck_vehicle_capacity'),
    sa.CheckConstraint('version >= 1', name='ck_vehicle_version'),
    sa.ForeignKeyConstraint(['tenant_id', 'driver_id'], ['driver.tenant_id', 'driver.driver_id'], name='fk_vehicle_tenant_driver', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'gps_device'], ['device.tenant_id', 'device.device_id'], name='fk_vehicle_tenant_device', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('vehicle_id'),
    sa.UniqueConstraint('tenant_id', 'plate_number', name='uq_vehicle_tenant_plate'),
    sa.UniqueConstraint('tenant_id', 'vehicle_code', name='uq_vehicle_tenant_code'),
    sa.UniqueConstraint('tenant_id', 'vehicle_id', name='uq_vehicle_tenant_id')
    )
    op.create_index('ix_vehicle_created_at', 'vehicle', ['created_at'], unique=False)
    op.create_index('ix_vehicle_location', 'vehicle', ['location'], unique=False, postgresql_using='gist')
    op.create_index('ix_vehicle_tenant_device', 'vehicle', ['tenant_id', 'gps_device'], unique=False)
    op.create_index('ix_vehicle_tenant_driver', 'vehicle', ['tenant_id', 'driver_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vehicle_tenant_driver', table_name='vehicle')
    op.drop_index('ix_vehicle_tenant_device', table_name='vehicle')
    op.drop_index('ix_vehicle_location', table_name='vehicle', postgresql_using='gist')
    op.drop_index('ix_vehicle_created_at', table_name='vehicle')
    op.drop_table('vehicle')
    op.drop_index('ix_school_tenant_kitchen', table_name='school')
    op.drop_index('ix_school_location', table_name='school', postgresql_using='gist')
    op.drop_index('ix_school_created_at', table_name='school')
    op.drop_table('school')
    op.drop_index('ix_driver_created_at', table_name='driver')
    op.drop_table('driver')
    # ### end Alembic commands ###
