"""storage_zone_device

Revision ID: 20260911_0002
Revises: 20260911_0001
Create Date: 2026-09-11 06:43:13.017076
"""
import geoalchemy2
import sqlalchemy as sa

from alembic import op

revision = '20260911_0002'
down_revision = '20260911_0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage',
    sa.Column('storage_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('kitchen_id', sa.Uuid(), nullable=False),
    sa.Column('storage_code', sa.String(length=50), nullable=False),
    sa.Column('storage_name', sa.String(length=200), nullable=False),
    sa.Column('storage_type', sa.String(length=50), nullable=False),
    sa.Column('temperature_min', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('temperature_max', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='ACTIVE', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('temperature_min <= temperature_max', name='ck_storage_temperature_range'),
    sa.CheckConstraint('version >= 1', name='ck_storage_version'),
    sa.ForeignKeyConstraint(['tenant_id', 'kitchen_id'], ['kitchen.tenant_id', 'kitchen.kitchen_id'], name='fk_storage_tenant_kitchen', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('storage_id'),
    sa.UniqueConstraint('kitchen_id', 'storage_code', name='uq_storage_kitchen_code'),
    sa.UniqueConstraint('tenant_id', 'storage_id', name='uq_storage_tenant_id')
    )
    op.create_index('ix_storage_created_at', 'storage', ['created_at'], unique=False)
    op.create_index('ix_storage_location', 'storage', ['location'], unique=False, postgresql_using='gist')
    op.create_index('ix_storage_tenant_kitchen', 'storage', ['tenant_id', 'kitchen_id'], unique=False)
    op.create_table('storage_zone',
    sa.Column('zone_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('storage_id', sa.Uuid(), nullable=False),
    sa.Column('zone_code', sa.String(length=50), nullable=False),
    sa.Column('zone_name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('version >= 1', name='ck_zone_version'),
    sa.ForeignKeyConstraint(['tenant_id', 'storage_id'], ['storage.tenant_id', 'storage.storage_id'], name='fk_zone_tenant_storage', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('zone_id'),
    sa.UniqueConstraint('storage_id', 'zone_code', name='uq_zone_storage_code'),
    sa.UniqueConstraint('tenant_id', 'zone_id', name='uq_zone_tenant_id')
    )
    op.create_index('ix_zone_created_at', 'storage_zone', ['created_at'], unique=False)
    op.create_index('ix_zone_tenant_storage', 'storage_zone', ['tenant_id', 'storage_id'], unique=False)
    op.create_table('device',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('device_uuid', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('zone_id', sa.Uuid(), nullable=True),
    sa.Column('device_name', sa.String(length=200), nullable=False),
    sa.Column('device_type', sa.String(length=50), nullable=False),
    sa.Column('firmware', sa.String(length=100), nullable=True),
    sa.Column('hardware', sa.String(length=100), nullable=True),
    sa.Column('mqtt_topic', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='REGISTERED', nullable=False),
    sa.Column('last_online', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('version >= 1', name='ck_device_version'),
    sa.ForeignKeyConstraint(['tenant_id', 'zone_id'], ['storage_zone.tenant_id', 'storage_zone.zone_id'], name='fk_device_tenant_zone', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('device_id'),
    sa.UniqueConstraint('device_uuid', name='uq_device_uuid'),
    sa.UniqueConstraint('tenant_id', 'device_id', name='uq_device_tenant_id')
    )
    op.create_index('ix_device_created_at', 'device', ['created_at'], unique=False)
    op.create_index('ix_device_tenant_zone', 'device', ['tenant_id', 'zone_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_device_tenant_zone', table_name='device')
    op.drop_index('ix_device_created_at', table_name='device')
    op.drop_table('device')
    op.drop_index('ix_zone_tenant_storage', table_name='storage_zone')
    op.drop_index('ix_zone_created_at', table_name='storage_zone')
    op.drop_table('storage_zone')
    op.drop_index('ix_storage_tenant_kitchen', table_name='storage')
    op.drop_index('ix_storage_location', table_name='storage', postgresql_using='gist')
    op.drop_index('ix_storage_created_at', table_name='storage')
    op.drop_table('storage')
    # ### end Alembic commands ###
