"""school_consumption_workflow

Revision ID: 20260911_0022
Revises: 20260911_0021
Create Date: 2026-09-11 22:14:23.415162
"""
import sqlalchemy as sa

from alembic import op

revision = '20260911_0022'
down_revision = '20260911_0021'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consumption', sa.Column('school_receiving_id', sa.Uuid(), nullable=True))
    op.add_column('consumption', sa.Column('consumed_quantity', sa.Numeric(precision=14, scale=6), nullable=True))
    op.add_column('consumption', sa.Column('discarded_quantity', sa.Numeric(precision=14, scale=6), nullable=True))
    op.add_column('consumption', sa.Column('notes', sa.String(length=2000), nullable=True))
    op.add_column('consumption', sa.Column('uom', sa.String(length=30), nullable=True))
    op.add_column('consumption', sa.Column('timer_status', sa.String(length=30), nullable=True))
    op.create_foreign_key('fk_consumption_school_receiving', 'consumption', 'school_receiving', ['tenant_id', 'school_receiving_id'], ['tenant_id', 'school_receiving_id'], ondelete='RESTRICT')
    op.add_column('school_receiving', sa.Column('expected_quantity', sa.Numeric(precision=14, scale=6), nullable=True))
    op.add_column('school_receiving', sa.Column('received_quantity', sa.Numeric(precision=14, scale=6), nullable=True))
    op.add_column('school_receiving', sa.Column('condition', sa.String(length=20), nullable=True))
    op.add_column('school_receiving', sa.Column('notes', sa.String(length=2000), nullable=True))
    op.add_column('school_receiving', sa.Column('uom', sa.String(length=30), nullable=True))
    op.add_column('school_receiving', sa.Column('timer_status', sa.String(length=30), nullable=True))
    op.create_check_constraint("ck_school_receiving_expected_quantity", "school_receiving", "expected_quantity IS NULL OR (expected_quantity > 0 AND expected_quantity < 'Infinity'::numeric)")
    op.create_check_constraint("ck_school_receiving_received_quantity", "school_receiving", "received_quantity IS NULL OR (received_quantity >= 0 AND received_quantity <= expected_quantity AND received_quantity < 'Infinity'::numeric)")
    op.execute('CREATE TRIGGER school_receiving_immutable BEFORE UPDATE OR DELETE ON school_receiving FOR EACH ROW EXECUTE FUNCTION public.fsos_reject_event_mutation()')
    op.execute('CREATE TRIGGER school_receiving_no_truncate BEFORE TRUNCATE ON school_receiving FOR EACH STATEMENT EXECUTE FUNCTION public.fsos_reject_event_mutation()')
    op.create_check_constraint("ck_consumption_consumed_quantity", "consumption", "consumed_quantity IS NULL OR (consumed_quantity >= 0 AND consumed_quantity < 'Infinity'::numeric)")
    op.create_check_constraint("ck_consumption_discarded_quantity", "consumption", "discarded_quantity IS NULL OR (discarded_quantity >= 0 AND discarded_quantity < 'Infinity'::numeric)")
    op.execute('CREATE TRIGGER consumption_immutable BEFORE UPDATE OR DELETE ON consumption FOR EACH ROW EXECUTE FUNCTION public.fsos_reject_event_mutation()')
    op.execute('CREATE TRIGGER consumption_no_truncate BEFORE TRUNCATE ON consumption FOR EACH STATEMENT EXECUTE FUNCTION public.fsos_reject_event_mutation()')
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute('DROP TRIGGER school_receiving_immutable ON school_receiving')
    op.execute('DROP TRIGGER school_receiving_no_truncate ON school_receiving')
    op.drop_constraint('ck_school_receiving_expected_quantity', 'school_receiving', type_='check')
    op.drop_constraint('ck_school_receiving_received_quantity', 'school_receiving', type_='check')
    op.execute('DROP TRIGGER consumption_immutable ON consumption')
    op.execute('DROP TRIGGER consumption_no_truncate ON consumption')
    op.drop_constraint('ck_consumption_consumed_quantity', 'consumption', type_='check')
    op.drop_constraint('ck_consumption_discarded_quantity', 'consumption', type_='check')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('school_receiving', 'timer_status')
    op.drop_column('school_receiving', 'uom')
    op.drop_column('school_receiving', 'notes')
    op.drop_column('school_receiving', 'condition')
    op.drop_column('school_receiving', 'received_quantity')
    op.drop_column('school_receiving', 'expected_quantity')
    op.drop_constraint('fk_consumption_school_receiving', 'consumption', type_='foreignkey')
    op.drop_column('consumption', 'timer_status')
    op.drop_column('consumption', 'uom')
    op.drop_column('consumption', 'notes')
    op.drop_column('consumption', 'discarded_quantity')
    op.drop_column('consumption', 'consumed_quantity')
    op.drop_column('consumption', 'school_receiving_id')
    # ### end Alembic commands ###
