"""packaging_holding

Revision ID: 20260911_0020
Revises: 20260911_0019
Create Date: 2026-09-11 21:49:26.779577
"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = '20260911_0020'
down_revision = '20260911_0019'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package', sa.Column('quantity', sa.Numeric(precision=14, scale=6), nullable=True))
    op.add_column('package', sa.Column('holding_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('package', sa.Column('holding_finished_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('production_batch', sa.Column('holding_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_check_constraint('ck_package_quantity', 'package', "quantity IS NULL OR (quantity > 0 AND quantity <> 'NaN'::numeric)")
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_constraint('ck_package_quantity', 'package', type_='check')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('production_batch', 'holding_policy')
    op.drop_column('package', 'holding_finished_at')
    op.drop_column('package', 'holding_started_at')
    op.drop_column('package', 'quantity')
    # ### end Alembic commands ###
