"""operational_event_log

Revision ID: 20260911_0012
Revises: 20260911_0011
Create Date: 2026-09-11 08:28:22.450557
"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = '20260911_0012'
down_revision = '20260911_0011'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_log',
    sa.Column('event_uuid', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_uuid', sa.Uuid(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("jsonb_typeof(payload) = 'object'", name='ck_event_payload'),
    sa.CheckConstraint('deleted_at IS NULL AND deleted_by IS NULL', name='ck_event_not_deleted'),
    sa.CheckConstraint('length(trim(entity_type)) > 0', name='ck_event_entity_type'),
    sa.CheckConstraint('length(trim(event_type)) > 0', name='ck_event_type'),
    sa.CheckConstraint('version >= 1', name='ck_event_version'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('event_uuid'),
    sa.UniqueConstraint('tenant_id', 'event_uuid', name='uq_event_tenant_uuid')
    )
    op.create_index('ix_event_created_at', 'event_log', ['created_at'], unique=False)
    op.create_index('ix_event_entity_timeline', 'event_log', ['tenant_id', 'entity_type', 'entity_uuid', 'created_at'], unique=False)
    op.create_index('ix_event_type_timeline', 'event_log', ['tenant_id', 'event_type', 'created_at'], unique=False)
    # ### end Alembic commands ###


    op.execute("""
        CREATE FUNCTION public.fsos_reject_event_mutation() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'Event history is append-only' USING ERRCODE = '55000';
        END;
        $$;
    """)
    op.execute("""
        CREATE TRIGGER event_log_immutable BEFORE UPDATE OR DELETE ON event_log
        FOR EACH ROW EXECUTE FUNCTION public.fsos_reject_event_mutation();
    """)
    op.execute("""
        CREATE TRIGGER event_log_no_truncate BEFORE TRUNCATE ON event_log
        FOR EACH STATEMENT EXECUTE FUNCTION public.fsos_reject_event_mutation();
    """)


def downgrade() -> None:
    op.execute('DROP TRIGGER event_log_immutable ON event_log')
    op.execute('DROP TRIGGER event_log_no_truncate ON event_log')
    op.execute('DROP FUNCTION public.fsos_reject_event_mutation()')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_event_type_timeline', table_name='event_log')
    op.drop_index('ix_event_entity_timeline', table_name='event_log')
    op.drop_index('ix_event_created_at', table_name='event_log')
    op.drop_table('event_log')
    # ### end Alembic commands ###
