"""partitioned_sensor_telemetry

Revision ID: 20260911_0013
Revises: 20260911_0012
Create Date: 2026-09-11 08:35:33.919226
"""
import geoalchemy2
import sqlalchemy as sa

from alembic import op

revision = '20260911_0013'
down_revision = '20260911_0012'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_unique_constraint('uq_device_tenant_uuid', 'device', ['tenant_id', 'device_uuid'])
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mqtt_message_log',
    sa.Column('message_uuid', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('topic', sa.String(length=65535), nullable=False),
    sa.Column('qos', sa.Integer(), nullable=False),
    sa.Column('payload', sa.LargeBinary(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('deleted_at IS NULL AND deleted_by IS NULL', name='ck_mqtt_message_not_deleted'),
    sa.CheckConstraint('length(trim(topic)) > 0', name='ck_mqtt_message_topic'),
    sa.CheckConstraint('qos BETWEEN 0 AND 2', name='ck_mqtt_message_qos'),
    sa.CheckConstraint('version >= 1', name='ck_mqtt_message_version'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('message_uuid'),
    sa.UniqueConstraint('tenant_id', 'message_uuid', name='uq_mqtt_message_tenant_uuid')
    )
    op.create_index('ix_mqtt_message_tenant_received', 'mqtt_message_log', ['tenant_id', 'received_at'], unique=False)
    op.create_table('heartbeat_log',
    sa.Column('heartbeat_log_id', sa.Uuid(), nullable=False),
    sa.Column('device_uuid', sa.Uuid(), nullable=False),
    sa.Column('uptime', sa.BigInteger(), nullable=False),
    sa.Column('heap', sa.BigInteger(), nullable=True),
    sa.Column('firmware', sa.String(length=100), nullable=True),
    sa.Column('hardware', sa.String(length=100), nullable=True),
    sa.Column('wifi_signal', sa.Integer(), nullable=True),
    sa.Column('battery', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mqtt_message_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('battery BETWEEN 0 AND 100', name='ck_heartbeat_battery'),
    sa.CheckConstraint('deleted_at IS NULL AND deleted_by IS NULL', name='ck_heartbeat_not_deleted'),
    sa.CheckConstraint('heap >= 0', name='ck_heartbeat_heap'),
    sa.CheckConstraint('uptime >= 0', name='ck_heartbeat_uptime'),
    sa.CheckConstraint('version >= 1', name='ck_heartbeat_version'),
    sa.ForeignKeyConstraint(['tenant_id', 'device_uuid'], ['device.tenant_id', 'device.device_uuid'], name='fk_heartbeat_device', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'mqtt_message_id'], ['mqtt_message_log.tenant_id', 'mqtt_message_log.message_uuid'], name='fk_heartbeat_mqtt', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('heartbeat_log_id', 'recorded_at'),
    postgresql_partition_by='RANGE (recorded_at)'
    )
    op.create_index('ix_heartbeat_device_time', 'heartbeat_log', ['tenant_id', 'device_uuid', 'recorded_at'], unique=False)
    op.create_index('ix_heartbeat_mqtt', 'heartbeat_log', ['tenant_id', 'mqtt_message_id'], unique=False)
    op.create_index('ix_heartbeat_recorded', 'heartbeat_log', ['recorded_at'], unique=False)
    op.create_table('humidity_log',
    sa.Column('humidity_log_id', sa.Uuid(), nullable=False),
    sa.Column('device_uuid', sa.Uuid(), nullable=False),
    sa.Column('humidity', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mqtt_message_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('deleted_at IS NULL AND deleted_by IS NULL', name='ck_humidity_not_deleted'),
    sa.CheckConstraint('humidity BETWEEN 0 AND 100', name='ck_humidity_range'),
    sa.CheckConstraint('version >= 1', name='ck_humidity_version'),
    sa.ForeignKeyConstraint(['tenant_id', 'device_uuid'], ['device.tenant_id', 'device.device_uuid'], name='fk_humidity_device', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'mqtt_message_id'], ['mqtt_message_log.tenant_id', 'mqtt_message_log.message_uuid'], name='fk_humidity_mqtt', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('humidity_log_id', 'recorded_at'),
    postgresql_partition_by='RANGE (recorded_at)'
    )
    op.create_index('ix_humidity_device_time', 'humidity_log', ['tenant_id', 'device_uuid', 'recorded_at'], unique=False)
    op.create_index('ix_humidity_mqtt', 'humidity_log', ['tenant_id', 'mqtt_message_id'], unique=False)
    op.create_index('ix_humidity_recorded', 'humidity_log', ['recorded_at'], unique=False)
    op.create_table('temperature_log',
    sa.Column('temperature_log_id', sa.Uuid(), nullable=False),
    sa.Column('device_uuid', sa.Uuid(), nullable=False),
    sa.Column('storage_uuid', sa.Uuid(), nullable=True),
    sa.Column('temperature', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=1), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mqtt_message_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("temperature <> 'NaN'::numeric", name='ck_temperature_finite'),
    sa.CheckConstraint("unit IN ('C', 'F', 'K')", name='ck_temperature_unit'),
    sa.CheckConstraint('deleted_at IS NULL AND deleted_by IS NULL', name='ck_temperature_not_deleted'),
    sa.CheckConstraint('version >= 1', name='ck_temperature_version'),
    sa.ForeignKeyConstraint(['tenant_id', 'device_uuid'], ['device.tenant_id', 'device.device_uuid'], name='fk_temperature_device', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'mqtt_message_id'], ['mqtt_message_log.tenant_id', 'mqtt_message_log.message_uuid'], name='fk_temperature_mqtt', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'storage_uuid'], ['storage.tenant_id', 'storage.storage_id'], name='fk_temperature_storage', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('temperature_log_id', 'recorded_at'),
    postgresql_partition_by='RANGE (recorded_at)'
    )
    op.create_index('ix_temperature_device_time', 'temperature_log', ['tenant_id', 'device_uuid', 'recorded_at'], unique=False)
    op.create_index('ix_temperature_mqtt', 'temperature_log', ['tenant_id', 'mqtt_message_id'], unique=False)
    op.create_index('ix_temperature_recorded', 'temperature_log', ['recorded_at'], unique=False)
    op.create_index('ix_temperature_storage_time', 'temperature_log', ['tenant_id', 'storage_uuid', 'recorded_at'], unique=False)
    op.create_table('gps_log',
    sa.Column('gps_log_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_uuid', sa.Uuid(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('speed', sa.Numeric(precision=9, scale=3), nullable=True),
    sa.Column('heading', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('altitude', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('hdop', sa.Numeric(precision=9, scale=3), nullable=True),
    sa.Column('satellite', sa.Integer(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), sa.Computed('ST_SetSRID(ST_MakePoint(longitude::double precision, latitude::double precision),4326)', persisted=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mqtt_message_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("altitude <> 'NaN'::numeric", name='ck_gps_altitude'),
    sa.CheckConstraint("hdop >= 0 AND hdop <> 'NaN'::numeric", name='ck_gps_hdop'),
    sa.CheckConstraint("speed >= 0 AND speed <> 'NaN'::numeric", name='ck_gps_speed'),
    sa.CheckConstraint('deleted_at IS NULL AND deleted_by IS NULL', name='ck_gps_not_deleted'),
    sa.CheckConstraint('heading >= 0 AND heading < 360', name='ck_gps_heading'),
    sa.CheckConstraint('latitude BETWEEN -90 AND 90', name='ck_gps_latitude'),
    sa.CheckConstraint('longitude BETWEEN -180 AND 180', name='ck_gps_longitude'),
    sa.CheckConstraint('satellite >= 0', name='ck_gps_satellite'),
    sa.CheckConstraint('version >= 1', name='ck_gps_version'),
    sa.ForeignKeyConstraint(['tenant_id', 'mqtt_message_id'], ['mqtt_message_log.tenant_id', 'mqtt_message_log.message_uuid'], name='fk_gps_mqtt', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'vehicle_uuid'], ['vehicle.tenant_id', 'vehicle.vehicle_id'], name='fk_gps_vehicle', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('gps_log_id', 'recorded_at'),
    postgresql_partition_by='RANGE (recorded_at)'
    )
    op.create_index('ix_gps_location', 'gps_log', ['location'], unique=False, postgresql_using='gist')
    op.create_index('ix_gps_mqtt', 'gps_log', ['tenant_id', 'mqtt_message_id'], unique=False)
    op.create_index('ix_gps_recorded', 'gps_log', ['recorded_at'], unique=False)
    op.create_index('ix_gps_vehicle_time', 'gps_log', ['tenant_id', 'vehicle_uuid', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


    op.execute("""
        CREATE FUNCTION public.fsos_reject_telemetry_mutation() RETURNS trigger
        LANGUAGE plpgsql AS $$ BEGIN
          RAISE EXCEPTION 'Telemetry evidence is append-only' USING ERRCODE='55000';
        END; $$;
    """)
    for table in ('temperature_log', 'humidity_log', 'gps_log', 'heartbeat_log', 'mqtt_message_log'):
        op.execute(f'CREATE TRIGGER telemetry_immutable BEFORE UPDATE OR DELETE ON {table} '
                   'FOR EACH ROW EXECUTE FUNCTION public.fsos_reject_telemetry_mutation()')
        op.execute(f'CREATE TRIGGER telemetry_no_truncate BEFORE TRUNCATE ON {table} '
                   'FOR EACH STATEMENT EXECUTE FUNCTION public.fsos_reject_telemetry_mutation()')
    op.execute("""
        CREATE FUNCTION public.fsos_create_telemetry_partitions(first_month date, month_count integer)
        RETURNS void LANGUAGE plpgsql AS $$
        DECLARE parent_name text; child_name text; month_start date; month_end date; offset_month integer;
        BEGIN
          IF first_month IS NULL OR month_count IS NULL OR month_count NOT BETWEEN 1 AND 24
             OR extract(day FROM first_month) <> 1 THEN
            RAISE EXCEPTION 'Use the first day of a month and month_count 1..24';
          END IF;
          PERFORM pg_advisory_xact_lock(20260911, 13);
          FOREACH parent_name IN ARRAY ARRAY['temperature_log','humidity_log','gps_log','heartbeat_log'] LOOP
            FOR offset_month IN 0..month_count-1 LOOP
              month_start := (first_month + make_interval(months => offset_month))::date;
              month_end := (month_start + interval '1 month')::date;
              child_name := parent_name || '_' || to_char(month_start, 'YYYYMM');
              EXECUTE format('CREATE TABLE IF NOT EXISTS public.%I PARTITION OF public.%I '
                'FOR VALUES FROM (%L) TO (%L)', child_name, parent_name,
                month_start::text || ' 00:00:00+00', month_end::text || ' 00:00:00+00');
              IF NOT EXISTS (SELECT 1 FROM pg_inherits WHERE
                inhrelid=to_regclass('public.' || child_name) AND
                inhparent=to_regclass('public.' || parent_name)) THEN
                RAISE EXCEPTION 'Partition name already belongs to another relation: %', child_name;
              END IF;
              IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgrelid=to_regclass('public.' || child_name)
                             AND tgname='telemetry_no_truncate') THEN
                EXECUTE format('CREATE TRIGGER telemetry_no_truncate BEFORE TRUNCATE ON public.%I '
                  'FOR EACH STATEMENT EXECUTE FUNCTION public.fsos_reject_telemetry_mutation()', child_name);
              END IF;
            END LOOP;
          END LOOP;
        END; $$;
    """)
    # Batas tetap membuat revisi dapat direproduksi; bulan berikutnya lewat script maintenance.
    op.execute("SELECT public.fsos_create_telemetry_partitions(DATE '2026-09-01', 3)")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_gps_vehicle_time', table_name='gps_log')
    op.drop_index('ix_gps_recorded', table_name='gps_log')
    op.drop_index('ix_gps_mqtt', table_name='gps_log')
    op.drop_index('ix_gps_location', table_name='gps_log', postgresql_using='gist')
    op.drop_table('gps_log')
    op.drop_index('ix_temperature_storage_time', table_name='temperature_log')
    op.drop_index('ix_temperature_recorded', table_name='temperature_log')
    op.drop_index('ix_temperature_mqtt', table_name='temperature_log')
    op.drop_index('ix_temperature_device_time', table_name='temperature_log')
    op.drop_table('temperature_log')
    op.drop_index('ix_humidity_recorded', table_name='humidity_log')
    op.drop_index('ix_humidity_mqtt', table_name='humidity_log')
    op.drop_index('ix_humidity_device_time', table_name='humidity_log')
    op.drop_table('humidity_log')
    op.drop_index('ix_heartbeat_recorded', table_name='heartbeat_log')
    op.drop_index('ix_heartbeat_mqtt', table_name='heartbeat_log')
    op.drop_index('ix_heartbeat_device_time', table_name='heartbeat_log')
    op.drop_table('heartbeat_log')
    op.drop_index('ix_mqtt_message_tenant_received', table_name='mqtt_message_log')
    op.drop_table('mqtt_message_log')
    op.drop_constraint('uq_device_tenant_uuid', 'device', type_='unique')
    op.execute('DROP FUNCTION public.fsos_create_telemetry_partitions(date, integer)')
    op.execute('DROP FUNCTION public.fsos_reject_telemetry_mutation()')
    # ### end Alembic commands ###
