"""consumption_complaint_recall

Revision ID: 20260911_0010
Revises: 20260911_0009
Create Date: 2026-09-11 07:20:33.231514
"""
import sqlalchemy as sa

from alembic import op

revision = '20260911_0010'
down_revision = '20260911_0009'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recall',
    sa.Column('recall_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('production_batch_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('completed_at IS NULL OR completed_at >= started_at', name='ck_recall_time_order'),
    sa.CheckConstraint('length(trim(reason)) > 0', name='ck_recall_reason'),
    sa.CheckConstraint('version >= 1', name='ck_recall_version'),
    sa.ForeignKeyConstraint(['tenant_id', 'production_batch_id'], ['production_batch.tenant_id', 'production_batch.production_batch_id'], name='fk_recall_production', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('recall_id'),
    sa.UniqueConstraint('tenant_id', 'recall_id', name='uq_recall_tenant_id')
    )
    op.create_index('ix_recall_created_at', 'recall', ['created_at'], unique=False)
    op.create_index('ix_recall_started_at', 'recall', ['started_at'], unique=False)
    op.create_index('ix_recall_tenant_production', 'recall', ['tenant_id', 'production_batch_id'], unique=False)
    op.create_table('complaint',
    sa.Column('complaint_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('package_id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('length(trim(description)) > 0', name='ck_complaint_description'),
    sa.CheckConstraint('version >= 1', name='ck_complaint_version'),
    sa.ForeignKeyConstraint(['tenant_id', 'package_id'], ['package.tenant_id', 'package.package_id'], name='fk_complaint_package', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'school_id'], ['school.tenant_id', 'school.school_id'], name='fk_complaint_school', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('complaint_id'),
    sa.UniqueConstraint('tenant_id', 'complaint_id', name='uq_complaint_tenant_id')
    )
    op.create_index('ix_complaint_created_at', 'complaint', ['created_at'], unique=False)
    op.create_index('ix_complaint_reported_at', 'complaint', ['reported_at'], unique=False)
    op.create_index('ix_complaint_tenant_package', 'complaint', ['tenant_id', 'package_id'], unique=False)
    op.create_index('ix_complaint_tenant_school', 'complaint', ['tenant_id', 'school_id'], unique=False)
    op.create_table('consumption',
    sa.Column('consumption_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('package_id', sa.Uuid(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('remaining_minutes', sa.Integer(), nullable=True),
    sa.Column('safe', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('version >= 1', name='ck_consumption_version'),
    sa.ForeignKeyConstraint(['tenant_id', 'package_id'], ['package.tenant_id', 'package.package_id'], name='fk_consumption_package', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('consumption_id'),
    sa.UniqueConstraint('tenant_id', 'consumption_id', name='uq_consumption_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'package_id', name='uq_consumption_package')
    )
    op.create_index('ix_consumption_consumed_at', 'consumption', ['consumed_at'], unique=False)
    op.create_index('ix_consumption_created_at', 'consumption', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_consumption_created_at', table_name='consumption')
    op.drop_index('ix_consumption_consumed_at', table_name='consumption')
    op.drop_table('consumption')
    op.drop_index('ix_complaint_tenant_school', table_name='complaint')
    op.drop_index('ix_complaint_tenant_package', table_name='complaint')
    op.drop_index('ix_complaint_reported_at', table_name='complaint')
    op.drop_index('ix_complaint_created_at', table_name='complaint')
    op.drop_table('complaint')
    op.drop_index('ix_recall_tenant_production', table_name='recall')
    op.drop_index('ix_recall_started_at', table_name='recall')
    op.drop_index('ix_recall_created_at', table_name='recall')
    op.drop_table('recall')
    # ### end Alembic commands ###
