"""digital_asset_relationship_movement

Revision ID: 20260911_0011
Revises: 20260911_0010
Create Date: 2026-09-11 08:24:15.545289
"""
import sqlalchemy as sa

from alembic import op

revision = '20260911_0011'
down_revision = '20260911_0010'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('digital_asset',
    sa.Column('asset_uuid', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('entity_uuid', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='CREATED', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('length(trim(asset_type)) > 0', name='ck_asset_type'),
    sa.CheckConstraint('length(trim(code)) > 0', name='ck_asset_code'),
    sa.CheckConstraint('version >= 1', name='ck_asset_version'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('asset_uuid'),
    sa.UniqueConstraint('tenant_id', 'asset_type', 'code', name='uq_asset_code'),
    sa.UniqueConstraint('tenant_id', 'asset_type', 'entity_uuid', name='uq_asset_entity'),
    sa.UniqueConstraint('tenant_id', 'asset_uuid', 'asset_type', name='uq_asset_tenant_type'),
    sa.UniqueConstraint('tenant_id', 'asset_uuid', name='uq_asset_tenant_uuid')
    )
    op.create_index('ix_asset_created_at', 'digital_asset', ['created_at'], unique=False)
    op.create_table('asset_movement',
    sa.Column('movement_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('asset_uuid', sa.Uuid(), nullable=False),
    sa.Column('movement_type', sa.String(length=30), nullable=False),
    sa.Column('from_location', sa.Uuid(), nullable=True),
    sa.Column('to_location', sa.Uuid(), nullable=True),
    sa.Column('operator', sa.Uuid(), nullable=True),
    sa.Column('movement_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("movement_type IN ('RECEIVING','STORAGE','ISSUE','PRODUCTION','PACKAGING','VEHICLE_LOADING','DELIVERY','SCHOOL_RECEIVING','CONSUMED','COMPLAINT','RECALL','DISCARD')", name='ck_movement_type'),
    sa.CheckConstraint('deleted_at IS NULL AND deleted_by IS NULL', name='ck_movement_not_deleted'),
    sa.CheckConstraint('version >= 1', name='ck_movement_version'),
    sa.ForeignKeyConstraint(['tenant_id', 'asset_uuid', 'asset_type'], ['digital_asset.tenant_id', 'digital_asset.asset_uuid', 'digital_asset.asset_type'], name='fk_movement_asset_type', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'from_location'], ['digital_asset.tenant_id', 'digital_asset.asset_uuid'], name='fk_movement_from', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'operator'], ['app_user.tenant_id', 'app_user.user_id'], name='fk_movement_operator', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'to_location'], ['digital_asset.tenant_id', 'digital_asset.asset_uuid'], name='fk_movement_to', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('movement_id'),
    sa.UniqueConstraint('tenant_id', 'movement_id', name='uq_movement_tenant_id')
    )
    op.create_index('ix_movement_asset_time', 'asset_movement', ['tenant_id', 'asset_uuid', 'movement_time'], unique=False)
    op.create_index('ix_movement_created_at', 'asset_movement', ['created_at'], unique=False)
    op.create_index('ix_movement_tenant_from', 'asset_movement', ['tenant_id', 'from_location'], unique=False)
    op.create_index('ix_movement_tenant_operator', 'asset_movement', ['tenant_id', 'operator'], unique=False)
    op.create_index('ix_movement_tenant_to', 'asset_movement', ['tenant_id', 'to_location'], unique=False)
    op.create_table('asset_relationship',
    sa.Column('relationship_uuid', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('parent_uuid', sa.Uuid(), nullable=False),
    sa.Column('child_uuid', sa.Uuid(), nullable=False),
    sa.Column('relationship_type', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("relationship_type IN ('SUPPLIED','STORED','USED','PRODUCED','PACKAGED','LOADED','DELIVERED','RECEIVED','CONSUMED','REPORTED','RECALLED')", name='ck_relationship_type'),
    sa.CheckConstraint('parent_uuid <> child_uuid', name='ck_relationship_self'),
    sa.CheckConstraint('version >= 1', name='ck_relationship_version'),
    sa.ForeignKeyConstraint(['tenant_id', 'child_uuid'], ['digital_asset.tenant_id', 'digital_asset.asset_uuid'], name='fk_relationship_child', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'parent_uuid'], ['digital_asset.tenant_id', 'digital_asset.asset_uuid'], name='fk_relationship_parent', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('relationship_uuid'),
    sa.UniqueConstraint('tenant_id', 'parent_uuid', 'child_uuid', 'relationship_type', name='uq_relationship_edge'),
    sa.UniqueConstraint('tenant_id', 'relationship_uuid', name='uq_relationship_tenant_uuid')
    )
    op.create_index('ix_relationship_created_at', 'asset_relationship', ['created_at'], unique=False)
    op.create_index('ix_relationship_tenant_child', 'asset_relationship', ['tenant_id', 'child_uuid'], unique=False)
    # ### end Alembic commands ###


    op.execute("""
        CREATE FUNCTION public.fsos_reject_movement_mutation() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'Asset movement history is append-only' USING ERRCODE = '55000';
        END;
        $$;
    """)
    op.execute("""
        CREATE TRIGGER asset_movement_immutable
        BEFORE UPDATE OR DELETE ON asset_movement
        FOR EACH ROW EXECUTE FUNCTION public.fsos_reject_movement_mutation();
    """)
    op.execute("""
        CREATE TRIGGER asset_movement_no_truncate
        BEFORE TRUNCATE ON asset_movement
        FOR EACH STATEMENT EXECUTE FUNCTION public.fsos_reject_movement_mutation();
    """)


def downgrade() -> None:
    op.execute('DROP TRIGGER asset_movement_immutable ON asset_movement')
    op.execute('DROP TRIGGER asset_movement_no_truncate ON asset_movement')
    op.execute('DROP FUNCTION public.fsos_reject_movement_mutation()')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_relationship_tenant_child', table_name='asset_relationship')
    op.drop_index('ix_relationship_created_at', table_name='asset_relationship')
    op.drop_table('asset_relationship')
    op.drop_index('ix_movement_tenant_to', table_name='asset_movement')
    op.drop_index('ix_movement_tenant_operator', table_name='asset_movement')
    op.drop_index('ix_movement_tenant_from', table_name='asset_movement')
    op.drop_index('ix_movement_created_at', table_name='asset_movement')
    op.drop_index('ix_movement_asset_time', table_name='asset_movement')
    op.drop_table('asset_movement')
    op.drop_index('ix_asset_created_at', table_name='digital_asset')
    op.drop_table('digital_asset')
    # ### end Alembic commands ###
